#!/bin/sh

usage()
{
	echo "usage: $0 start|restart|stop|help"
	exit 1
}

_help()
{
	echo "$0 command"
	echo "bourse start: démmarre l'application"
	echo "bourse stop: arrete l'application"
	echo "bourse restart: redémarre l'application (équivalent à stop suivi de restart)"
	echo "bourse help: affiche cette aide."
	exit 2
}

if [ $# -eq 0 ]
then
	usage;
fi

dir=`dirname $0`
cd $dir # pwd = racine de l'application

case $1 in
start|stop)
	scripts/$1.sh
	;;
restart)
	echo 'restarting...'
	scripts/stop.sh
	scripts/start.sh
	;;
'help')
	_help;
	;;
*)
	usage;
	;;
esac
